language: node_js
node_js:
  - "7"

os: 
  - linux
  - osx
# dist: trusty
# sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2

cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.npm
  - $HOME/.nvm

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils

install:
  - node --version
  - npm --version
  - npm install

script:
#  - npm run test
# - npm run build
  # - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; npm run build:linux ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; find . | grep AppImage ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; bash upload.sh ./dist/subtitles-composer-app-*-x86_64.AppImage ; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; npm run build:mac; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; find . | grep dmg ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; bash upload.sh ./dist/subtitles-composer-app-*.dmg ; fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/